# use tmux source-file ~/.tmux.conf command after saving this file
set -g mouse on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'


bind -r h select-pane -L
bind -r l select-pane -R
bind -r k select-pane -U
bind -r j select-pane -D

run '/Users/sharoha/.tmux/plugins/tpm/tpm'
